// Family tree of Jiří Votava – data. GENERATED by datatool.js – edit via datatool, not by hand/regex.
// cert: M = read in a parish/civil register, D = other document, R = family tradition, K = candidate / unverified
window.RODOKMEN = {
  updated: "8. 10. 2026",
  root: "jiri1987",
  publicLiving: "full",
  lines: {
    "votava": "Votava",
    "cervenka": "Červenka",
    "zettelmann": "Zettelmann",
    "hrazdilek": "Hrazdílek",
    "blazek": "Blažek",
    "jerabek": "Jeřábek",
    "hromas": "Hromas",
    "voticky": "Votický",
    "nezname": "zatím neznámý",
    "capek": "Čapek",
    "klika": "Klika",
    "valenta": "Valenta",
    "vlasak": "Vlasák",
    "lodl": "Lodl",
    "michal": "Michal",
    "fukal": "Tůkal",
    "svoboda": "Svoboda",
    "ota": "Ota (?)",
    "snajdr": "Šnajdr",
    "forejt": "Forejt",
    "divis": "Diviš",
    "merhaut": "Merhaut",
    "skala": "Skála",
    "kalous": "Kalous",
    "holicky": "Holický",
    "zyma": "Zyma",
    "drapal": "Drapal",
    "novy": "Nový",
    "semenec": "Semenec"
  },
  people: [
    {
      id: "jiri1987",
      name: "Jiří Votava",
      line: "votava",
      cert: "D",
      b: {"date":"2. 2. 1987","year":1987,"place":"Vítkov č. p. 89, okr. Opava"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Výchozí osoba rodokmenu. Druhý syn Jana a Šárky Votavových."
      ],
      sources: [
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "martin1984",
      name: "Martin Votava",
      line: "votava",
      cert: "D",
      b: {"date":"14. 8. 1984","year":1984,"place":"Vítkov, Opavská č. p. 89, okr. Opava"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "První syn Jana a Šárky."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jan1993",
      name: "Jan Votava",
      line: "votava",
      cert: "D",
      b: {"date":"13. 3. 1993","year":1993,"place":"Chomutov (nemocnice)"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Třetí syn Jana a Šárky, v rodině „Jenda“."
      ],
      sources: [
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "frantisek2000",
      name: "František Votava",
      line: "votava",
      cert: "D",
      b: {"date":"16. 6. 2000","year":2000,"place":"Chomutov (nemocnice)"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Čtvrtý syn Jana a Šárky."
      ],
      sources: [
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jan1957",
      name: "Jan Votava",
      line: "votava",
      cert: "D",
      b: {"date":"5. 3. 1957","year":1957,"place":"Beroun"},
      father: "vaclav1933",
      mother: "anna1933",
      spouse: "sarka1963",
      alive: true,
      occ: "student (1984); soukromý podnikatel (1993); Ing., podnikatel (2000)",
      notes: [
        "Rodiče Václav Votava a Anna, roz. Červenková – podle rodných listů synů.",
        "Bydliště podle rodných listů synů: Vítkov, okr. Opava (1984, 1987), Jirkov, okr. Chomutov (1993, 2000).",
        "Datum a místo sňatku se Šárkou Zettelmannovou zatím nezjištěno."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "sarka1963",
      name: "Šárka Votavová",
      maiden: "Zettelmannová",
      line: "zettelmann",
      cert: "D",
      b: {"date":"14. 4. 1963","year":1963,"place":"Karviná 4 – Ráj (nemocnice), okr. Karviná"},
      father: "frantisek1940",
      mother: "helena1940",
      spouse: "jan1957",
      alive: true,
      occ: "cenzurantka (1984); účetní (1993); referentka (2000)",
      notes: [
        "V roce 1963 bydleli rodiče v Karviné 4 – Ráj."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)"
      ]
    },
    {
      id: "jana1958",
      name: "Jana Hromasová",
      maiden: "Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"17. 5. 1958","year":1958},
      father: "vaclav1933",
      mother: "anna1933",
      spouse: "karel1964",
      alive: true,
      notes: [
        "Sestra Jana Votavy (*1957)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1964",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"9. 9. 1964","year":1964},
      father: "karel1937",
      mother: "vlasta1935",
      spouse: "jana1958",
      alive: true,
      notes: [
        "Manžel Jany Hromasové, roz. Votavové; v kalendáři „Karel Hromas (Beroun)“."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1986",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"27. 1. 1986","year":1986},
      mother: "jana1958",
      alive: true,
      notes: [
        "Syn Jany Hromasové, roz. Votavové; v kalendáři „Karel Hromas (Hokej)“, v rodinném rodokmenu mezi dětmi Jany.",
        "Otec výslovně neuveden – nejspíš Karel Hromas (*1964), manžel Jany (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "karel1937",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"2. 12. 1937","year":1937},
      notes: [
        "Otec Karla Hromase (*1964); v kalendáři „Karel Hromas (Rajč.)“."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vlasta1935",
      name: "Vlasta Hromasová",
      line: "nezname",
      cert: "R",
      b: {"date":"3. 3. 1935","year":1935},
      notes: [
        "Matka Karla Hromase (*1964) – v kalendáři „tchyně sestry Jany Votavové“.",
        "Rodné příjmení neznámé."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vaclav1933",
      name: "Václav Votava",
      line: "votava",
      cert: "D",
      b: {"date":"4. 9. 1933","year":1933,"place":"Souš č. p. 50 (Most)"},
      d: {"date":"4. 9. 2017","year":2017},
      father: "vaclav1899",
      mother: "jana1903",
      occ: "chemik (1956)",
      marriage: "11. 8. 1956, Kolín – s Annou Červenkovou",
      notes: [
        "Jako otec Jana Votavy (*1957) uveden na rodných listech jeho synů.",
        "V roce 1956 bydlel v Kopistech č. p. 241 u Mostu. Později žil v Chomutově, odkud psal obecnímu úřadu v Těchobuzi kvůli předkům Votavů.",
        "Datum úmrtí podle rodinného kalendáře. Rok je tam ručně opraven z 1947 na 2017 a úmrtí připadá na den 84. narozenin – ověřit (?)."
      ],
      sources: [
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Dopis Václava Votavy (*1933, Chomutov) Obecnímu úřadu Těchobuz, okr. Pelhřimov (nedatováno) – cituje křestní list Václava Votavy (*1899) z 9. 9. 1924 a výměr o domovském právu z 8. 9. 1940",
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ],
      scans: [
        {"f":"img/1933_rodny_list_vaclav_votava_sous.jpg","t":"Rodný list Václava Votavy, Souš 4. 9. 1933"},
        {"f":"img/dopis_vaclav_votava_techobuz.jpg","t":"Dopis Václava Votavy (*1933) obecnímu úřadu v Těchobuzi"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Oddací list Václava Votavy a Anny Červenkové, Kolín 11. 8. 1956"},
        {"f":"img/1940_vymer_domovske_pravo_vaclav_votava.jpg","t":"Výměr o domovském právu v Těchobuzi, Pelhřimov 8. 9. 1940"},
        {"f":"img/dopis_vaclav_votava_anicce_1.jpg","t":"Dopis Václava Votavy (*1933) vnučce Aničce, s. 1"},
        {"f":"img/dopis_vaclav_votava_anicce_2.jpg","t":"Dopis Václava Votavy vnučce – tabulka dat"}
      ]
    },
    {
      id: "anna1933",
      name: "Anna Votavová",
      maiden: "Červenková",
      line: "cervenka",
      cert: "D",
      b: {"date":"27. 2. 1933","year":1933,"place":"Suchomasty č. p. 31, okr. Beroun"},
      d: {"date":"2. 11. 2016","year":2016},
      father: "karel1906",
      mother: "anna1913",
      occ: "úřednice (1956)",
      marriage: "11. 8. 1956, Kolín – s Václavem Votavou",
      notes: [
        "V rodině „Hanka“. Pokřtěna 12. 3. 1933 v Borku u Suchomast; kmotra Anna Červenková z Berouna.",
        "V roce 1956 bydlela v Suchomastech č. p. 70.",
        "Datum úmrtí podle rodinného kalendáře."
      ],
      sources: [
        "Křestní a rodný list Anny Červenkové (*1933), fara Borek, kniha pokřtěných XIV, sv. 64, list 2 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ],
      scans: [
        {"f":"img/1933_krestni_list_anna_cervenkova_suchomasty.jpg","t":"Křestní list Anny Červenkové, Suchomasty 27. 2. 1933"},
        {"f":"img/1933_rodny_list_anna_cervenkova_suchomasty.jpg","t":"Rodný list Anny Červenkové (1933)"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Oddací list Václava Votavy a Anny Červenkové, Kolín 11. 8. 1956"}
      ]
    },
    {
      id: "jiri1926",
      name: "Jiří Votava",
      line: "votava",
      cert: "R",
      b: {"date":"3. 4. 1926","year":1926},
      d: {"date":"24. 4. 1980","year":1980},
      father: "vaclav1899",
      mother: "jana1903",
      spouse: "lidus1934",
      notes: [
        "Bratr Václava Votavy (*1933).",
        "Mezi dětmi uveden ve výměru o domovském právu 1940 (nar. 3. 4. 1926)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Výměr Okresního úřadu v Pelhřimově č. 30435/40 o určení domovského práva (8. 9. 1940)",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1940_vymer_domovske_pravo_vaclav_votava.jpg","t":"Výměr o domovském právu v Těchobuzi, Pelhřimov 8. 9. 1940"}
      ]
    },
    {
      id: "lidus1934",
      name: "Lída (Liduš) Votavová",
      line: "nezname",
      cert: "R",
      b: {"date":"23. 8. 1934","year":1934},
      d: {"date":"22. 8. 2004","year":2004},
      spouse: "jiri1926",
      notes: [
        "Manželka Jiřího Votavy (*1926).",
        "Rodné příjmení neznámé; „Liduš“ je nejspíš domácká podoba jména Ludmila (?).",
        "V dopise Václava (*1933) „Lída Votavová, 1934 – 22. 8. 2004, manželka Jiřího – Most“."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ]
    },
    {
      id: "jiri1954",
      name: "Jiří Votava",
      line: "votava",
      cert: "R",
      b: {"date":"4. 8. 1954","year":1954},
      d: {"date":"4. 3. 2008","year":2008},
      father: "jiri1926",
      notes: [
        "Syn Jiřího Votavy (*1926), bratranec Jana Votavy (*1957).",
        "Matka v kalendáři neuvedena."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "vlasta1927",
      name: "Vlasta Votická",
      maiden: "Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"2. 6. 1927","year":1927},
      d: {"date":"19. 4. 2008","year":2008},
      father: "vaclav1899",
      mother: "jana1903",
      spouse: "frantisek1919",
      notes: [
        "Sestra Václava Votavy (*1933).",
        "Mezi dětmi uvedena ve výměru o domovském právu 1940 (nar. 2. 6. 1927)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Výměr Okresního úřadu v Pelhřimově č. 30435/40 o určení domovského práva (8. 9. 1940)"
      ],
      scans: [
        {"f":"img/1940_vymer_domovske_pravo_vaclav_votava.jpg","t":"Výměr o domovském právu v Těchobuzi, Pelhřimov 8. 9. 1940"}
      ]
    },
    {
      id: "frantisek1919",
      name: "František Votický",
      line: "voticky",
      cert: "R",
      b: {"date":"9. 1. 1919","year":1919},
      d: {"date":"19. 6. 1982","year":1982},
      spouse: "vlasta1927",
      notes: [
        "Manžel Vlasty Votické, roz. Votavové.",
        "Žil v Litvínově (dopis Václava *1933)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ]
    },
    {
      id: "ivo1955",
      name: "Ivo Votický",
      line: "voticky",
      cert: "R",
      b: {"date":"16. 3. 1955","year":1955},
      mother: "vlasta1927",
      notes: [
        "Syn Vlasty Votické (*1927), bratranec Jana Votavy (*1957).",
        "Otec v kalendáři výslovně neuveden – nejspíš František Votický (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "vladik1942",
      name: "Vladimír Votava",
      line: "votava",
      cert: "D",
      b: {"date":"4. 1. 1942","year":1942,"place":"Kopisty č. p. 241 (Most)"},
      d: {"date":"7. 10. 1995","year":1995,"place":"Most"},
      cause: "chronický hnisavý zánět ledvin",
      father: "vaclav1899",
      mother: "jana1903",
      occ: "invalidní důchodce",
      notes: [
        "V rodině „Vladík“. Bratr Václava Votavy (*1933).",
        "Svobodný, bydlel v Mostě; zpopelněn v Mostě."
      ],
      sources: [
        "Rodný list Vladimíra Votavy (*1942), MNV Most (vydán 14. 5. 1957)",
        "Úmrtní list Vladimíra Votavy, MěÚ Most (vydán 23. 10. 1995)"
      ],
      scans: [
        {"f":"img/1942_rodny_list_vladimir_votava_kopisty.jpg","t":"Rodný list Vladimíra Votavy, Kopisty 4. 1. 1942"},
        {"f":"img/1995_umrtni_list_vladimir_votava_most.jpg","t":"Úmrtní list Vladimíra Votavy, Most 7. 10. 1995"}
      ]
    },
    {
      id: "frantisek1940",
      name: "František Zettelmann",
      line: "zettelmann",
      cert: "D",
      b: {"date":"26. 11. 1940","year":1940,"place":"Polouvsí, okr. Nový Jičín"},
      d: {"date":"8. 4. 1999","year":1999},
      father: "frantisek_z",
      mother: "ludmila_b",
      occ: "řidič (1963)",
      notes: [
        "Datum úmrtí podle rodinného kalendáře.",
        "Na rodném listu vnuka Jana (1993) zapsán jako „František Zettelmann roz. Zetelmann“ – příjmení se mohlo psát i s jedním t."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "helena1940",
      name: "Helena Zettelmannová",
      maiden: "Hrazdílková",
      line: "hrazdilek",
      cert: "D",
      b: {"date":"21. 10. 1940","year":1940,"place":"Heršpice, okr. Vyškov"},
      father: "vladimir_h",
      mother: "marie_j",
      occ: "zdravotní sestra (1963)",
      notes: [
        "Matka Šárky Votavové."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vaclav1899",
      name: "Václav Votava",
      line: "votava",
      cert: "D",
      b: {"date":"25. 10. 1899","year":1899,"place":"Souš č. p. 189 (Most)"},
      d: {"date":"11. 12. 1968","year":1968},
      father: "vaclav1868",
      mother: "barbora_l",
      spouse: "jana1903",
      occ: "horník",
      marriage: "18. 10. 1924, Most – s Janou Čapkovou",
      notes: [
        "Pokřtěn v Souši (farnost Souš, matrika tom. 14). Otec Václav Votava, horník; děd Štěpán Votava, horník v Souši; matka Barbora, dcera Martina Lodla, horníka v Souši.",
        "Horník. Domovské právo v Souši (domovský list 9. 9. 1924, svobodný).",
        "Bydliště: Komořany (1924), Souš č. p. 50 (1933), Souš č. p. 21 (1940), Kopisty č. p. 241 (1942, 1956).",
        "Výměrem Okresního úřadu v Pelhřimově z 8. 9. 1940 mu bylo přiděleno domovské právo v Těchobuzi (ke dni 7. 2. 1939): Souš připadla Německu, on se stal československým (protektorátním) státním občanem. Před nabytím domovského práva v Souši příslušel do Těchobuze po otci (do 27. 4. 1919). Domovské právo následovaly manželka a děti Jiří, Vlasta a Václav.",
        "Datum úmrtí podle rodinného kalendáře a dopisu syna („Děda (Most)“)."
      ],
      sources: [
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Rodný list Vladimíra Votavy (*1942), MNV Most (vydán 14. 5. 1957)",
        "Dopis Václava Votavy (*1933, Chomutov) Obecnímu úřadu Těchobuz, okr. Pelhřimov (nedatováno) – cituje křestní list Václava Votavy (*1899) z 9. 9. 1924 a výměr o domovském právu z 8. 9. 1940",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)",
        "Domovský list Václava Votavy, obec Souš, polit. okres Most, č. 415/24 (9. 9. 1924)",
        "Výtah z knihy křtěných a oddaných (sňatek 18. 10. 1924 Most), Okresní správa politická v Mostě, 24. 10. 1924",
        "Výměr Okresního úřadu v Pelhřimově č. 30435/40 o určení domovského práva (8. 9. 1940)",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1942_rodny_list_vladimir_votava_kopisty.jpg","t":"Rodný list syna Vladimíra (1942)"},
        {"f":"img/1933_rodny_list_vaclav_votava_sous.jpg","t":"Rodný list syna Václava (1933)"},
        {"f":"img/dopis_vaclav_votava_techobuz.jpg","t":"Dopis Václava Votavy (*1933) obecnímu úřadu v Těchobuzi"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Sňatek dětí Václava a Anny, Kolín 1956"},
        {"f":"img/rodokmen_kresba_votava.jpg","t":"Ručně kreslený rodokmen Votavů"},
        {"f":"img/1899_krestni_list_vaclav_votava_sous.jpg","t":"Křestní list Václava Votavy, Souš 25. 10. 1899 (vydán 1924)"},
        {"f":"img/1924_vytah_snatek_votava_capkova_most.jpg","t":"Výtah z matriky – sňatek 18. 10. 1924, Most"},
        {"f":"img/1940_vymer_domovske_pravo_vaclav_votava.jpg","t":"Výměr o domovském právu v Těchobuzi, Pelhřimov 8. 9. 1940"},
        {"f":"img/1924_domovsky_list_vaclav_votava_sous.jpg","t":"Domovský list Václava Votavy, Souš 1924"},
        {"f":"img/dopis_vaclav_votava_anicce_1.jpg","t":"Dopis Václava Votavy (*1933) vnučce Aničce, s. 1"},
        {"f":"img/dopis_vaclav_votava_anicce_2.jpg","t":"Dopis Václava Votavy vnučce – tabulka dat"}
      ]
    },
    {
      id: "jana1903",
      name: "Jana Votavová",
      maiden: "Čapková",
      line: "capek",
      cert: "D",
      b: {"date":"16. 5. 1903","year":1903,"place":"Mladá Boleslav č. p. 278-III"},
      d: {"date":"29. 7. 1984","year":1984,"place":"Most"},
      cause: "jaterní cirhóza",
      father: "josef_c",
      mother: "marie_f",
      spouse: "vaclav1899",
      occ: "dělnice (1956); důchodkyně (1984)",
      marriage: "18. 10. 1924, Most – s Václavem Votavou",
      notes: [
        "Pokřtěna 18. 5. 1903 v Mladé Boleslavi kaplanem Františkem Matějkou (matrika fol. 134).",
        "Rodiče Josef Čapek a Marie, roz. Tůkalová. Křestní list (1924) i úmrtní list (1984) mají Tůkalová / Tukalová; „Fukalová“ v rodném listu syna (1956) je chyba opisu (první písmeno přepsané na stroji).",
        "Domovské právo v Souši (domovský list 28. 5. 1931: manželka horníka – dělnice).",
        "Zemřela jako vdova v Mostě; zpopelněna 3. 8. 1984 v Mostě.",
        "Její rodiče Čapkovi bydleli v Komořanech u Mostu – syn Václav (*1933) je znal za první republiky a za války."
      ],
      sources: [
        "Úmrtní list Jany Votavové, MNV Most (vydán 15. 8. 1984)",
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Rodný list Vladimíra Votavy (*1942), MNV Most (vydán 14. 5. 1957)",
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134",
        "Výtah z knihy křtěných a oddaných (sňatek 18. 10. 1924 Most), Okresní správa politická v Mostě, 24. 10. 1924",
        "Domovský list Jany Votavové, obec Souš, č. 1023/31 (28. 5. 1931)",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1942_rodny_list_vladimir_votava_kopisty.jpg","t":"Rodný list syna Vladimíra (1942)"},
        {"f":"img/1933_rodny_list_vaclav_votava_sous.jpg","t":"Rodný list syna Václava (1933)"},
        {"f":"img/1984_umrtni_list_jana_votavova_most.jpg","t":"Úmrtní list Jany Votavové, Most 29. 7. 1984"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Sňatek dětí Václava a Anny, Kolín 1956"},
        {"f":"img/1903_krestni_list_jana_capkova_mlada_boleslav.jpg","t":"Křestní list Jany Čapkové, Mladá Boleslav 16. 5. 1903 (vydán 1924)"},
        {"f":"img/1924_vytah_snatek_votava_capkova_most.jpg","t":"Výtah z matriky – sňatek 18. 10. 1924, Most"},
        {"f":"img/1940_vymer_domovske_pravo_vaclav_votava.jpg","t":"Výměr o domovském právu v Těchobuzi, Pelhřimov 8. 9. 1940"},
        {"f":"img/1931_domovsky_list_jana_votavova_sous.jpg","t":"Domovský list Jany Votavové, Souš 1931"}
      ]
    },
    {
      id: "karel1906",
      name: "Karel Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"29. 4. 1906","year":1906,"place":"Beroun III č. p. 229 (Lištice)"},
      d: {"date":"8. 9. 1984","year":1984},
      father: "vaclav_c",
      mother: "anna_vl",
      spouse: "anna1913",
      occ: "dělník",
      marriage: "7. 1. 1933, Borek u Suchomast (kostel sv. Mikuláše) – s Annou Klikovou",
      notes: [
        "V kalendáři „Děda (Suchomasty)“. V roce 1933 bydlel v Berouně III č. p. 229.",
        "Datum úmrtí podle rodinného kalendáře.",
        "Rodopis Červenků uvádí narození „1906 na Lištici č. p. 83“ (rodný list dcery: Beroun III č. p. 229) a sňatek s Annou Klikovou."
      ],
      sources: [
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)",
        "Křestní a rodný list Anny Červenkové (*1933), fara Borek, kniha pokřtěných XIV, sv. 64, list 2 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny",
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/1933_oddaci_list_cervenka_klikova_borek.jpg","t":"Oddací list Karla Červenky a Anny Klikové, Borek 7. 1. 1933"},
        {"f":"img/1933_krestni_list_anna_cervenkova_suchomasty.jpg","t":"Křest dcery Anny, Suchomasty 1933"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Sňatek dětí Václava a Anny, Kolín 1956"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "anna1913",
      name: "Anna Červenková",
      maiden: "Kliková",
      line: "klika",
      cert: "D",
      b: {"date":"3. 4. 1913","year":1913,"place":"Suchomasty č. p. 14, okr. Beroun"},
      d: {"date":"25. 5. 1983","year":1983},
      father: "karel_k",
      mother: "ruzena_v",
      spouse: "karel1906",
      occ: "v domácnosti (1956)",
      marriage: "7. 1. 1933, Borek u Suchomast (kostel sv. Mikuláše) – s Karlem Červenkou",
      notes: [
        "Pokřtěna 6. 4. 1913 v Borku; kmotra Anna Prejsková (?) ze Suchomast.",
        "V kalendáři „Babička (Suchomasty)“; datum úmrtí podle kalendáře.",
        "Příjmení v oddacím a křestním listu ručně „Klihová“ (?), strojem v rodném listu dcery a v oddacím listu 1956 „Kliková“."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)",
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Oddací list Václava Votavy a Anny Červenkové, MNV Kolín, sv. III, roč. 1956, str. 216, č. 122 (vydán 11. 8. 1956)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ],
      scans: [
        {"f":"img/1933_oddaci_list_cervenka_klikova_borek.jpg","t":"Oddací list Karla Červenky a Anny Klikové, Borek 7. 1. 1933"},
        {"f":"img/1933_krestni_list_anna_cervenkova_suchomasty.jpg","t":"Křest dcery Anny, Suchomasty 1933"},
        {"f":"img/1913_krestni_list_anna_klikova_suchomasty.jpg","t":"Křestní list Anny Klikové, Suchomasty 3. 4. 1913"},
        {"f":"img/1956_oddaci_list_votava_cervenkova_kolin.jpg","t":"Sňatek dětí Václava a Anny, Kolín 1956"}
      ]
    },
    {
      id: "frantisek_z",
      name: "František Zettelmann",
      line: "zettelmann",
      cert: "D",
      b: {"date":"neznámé (odhad ~1912)","year":1912,"approx":true},
      notes: [
        "Otec Františka Zettelmanna (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "ludmila_b",
      name: "Ludmila Zettelmannová",
      maiden: "Blažková",
      line: "blazek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1915)","year":1915,"approx":true},
      notes: [
        "Matka Františka Zettelmanna (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "vladimir_h",
      name: "Vladimír Hrazdílek",
      line: "hrazdilek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1912)","year":1912,"approx":true},
      notes: [
        "Otec Heleny Zettelmannové (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "marie_j",
      name: "Marie Hrazdílková",
      maiden: "Jeřábková",
      line: "jerabek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1915)","year":1915,"approx":true},
      notes: [
        "Matka Heleny Zettelmannové (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "vaclav1868",
      name: "Václav Votava",
      line: "votava",
      cert: "D",
      b: {"date":"25. 8. 1868","year":1868,"place":"Pravonín"},
      d: {"date":"9. 11. 1963","year":1963,"place":"Souš (Most)"},
      father: "stepan_v",
      mother: "antonie_m",
      spouse: "barbora_l",
      occ: "horník",
      notes: [
        "Narozen 25. 8. 1868 v Pravoníně (výměr 1940). Syn Štěpána Votavy, horníka v Souši, a Antonie roz. Michalové z Těchobuze č. 19 (křestní list syna 1924).",
        "Podle rodinné tradice přišel do Mostu asi ve 4 letech (kolem 1872), kdy se na Mostecku otvíraly šachty; v Souši pak žil i jeho otec Štěpán.",
        "Domovské právo v Těchobuzi (okr. Pelhřimov) měl do 27. 4. 1919.",
        "Zemřel 9. 11. 1963 v 95 letech (dopis vnuka Václava, rodinná paměť).",
        "Děti podle rodinného rodokmenu: Václav (*1899), Eda, Josef, Zdeňka, Anna.",
        "KANDIDÁT: v Těchobuzi č. p. 76 žil roku 1951 František Votava (kronika obce) – příbuzenství neověřeno."
      ],
      sources: [
        "Dopis Václava Votavy (*1933, Chomutov) Obecnímu úřadu Těchobuz, okr. Pelhřimov (nedatováno) – cituje křestní list Václava Votavy (*1899) z 9. 9. 1924 a výměr o domovském právu z 8. 9. 1940",
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)",
        "Kronika obce Těchobuz, kap. Zemědělské družstvo v Těchobuzi, s. 149 (kopie u rodiny)",
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)",
        "Výměr Okresního úřadu v Pelhřimově č. 30435/40 o určení domovského práva (8. 9. 1940)",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1951_kronika_techobuz_frantisek_votava.jpg","t":"Kronika Těchobuze 1951 – František Votava č. p. 76"},
        {"f":"img/dopis_vaclav_votava_techobuz.jpg","t":"Dopis Václava Votavy (*1933) obecnímu úřadu v Těchobuzi"},
        {"f":"img/rodokmen_kresba_votava.jpg","t":"Ručně kreslený rodokmen Votavů"},
        {"f":"img/1899_krestni_list_vaclav_votava_sous.jpg","t":"Křest syna/vnuka Václava, Souš 1899"},
        {"f":"img/dopis_vaclav_votava_anicce_1.jpg","t":"Dopis Václava Votavy (*1933) vnučce Aničce, s. 1"},
        {"f":"img/dopis_vaclav_votava_anicce_2.jpg","t":"Dopis Václava Votavy vnučce – tabulka dat"}
      ]
    },
    {
      id: "barbora_l",
      name: "Barbora Votavová",
      maiden: "Lodlová",
      line: "lodl",
      cert: "D",
      b: {"date":"29. 6. 1869","year":1869},
      d: {"date":"16. 5. 1918","year":1918},
      father: "martin_l",
      mother: "anna_f",
      spouse: "vaclav1868",
      notes: [
        "Matka Václava Votavy (*1899). Dcera Martina Lodla, horníka v Souši č. 57 (?), a Anny roz. Forejtové z ? (Věka?) č. 91 (křestní list syna 1924).",
        "Data narození a úmrtí podle dopisu vnuka Václava (*1933) – rodinná paměť."
      ],
      sources: [
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1899_krestni_list_vaclav_votava_sous.jpg","t":"Křest syna/vnuka Václava, Souš 1899"},
        {"f":"img/dopis_vaclav_votava_anicce_1.jpg","t":"Dopis Václava Votavy (*1933) vnučce Aničce, s. 1"},
        {"f":"img/dopis_vaclav_votava_anicce_2.jpg","t":"Dopis Václava Votavy vnučce – tabulka dat"}
      ]
    },
    {
      id: "stepan_v",
      name: "Štěpán Votava",
      line: "votava",
      cert: "D",
      b: {"date":"neznámé (odhad ~1840)","year":1840,"approx":true},
      spouse: "antonie_m",
      occ: "horník v Souši",
      notes: [
        "Horník v Souši u Mostu (křestní list vnuka 1924); původem z Vysočiny, s rodinou z Těchobuze č. 19.",
        "Otec Václava Votavy (*1868), Těchobuz č. p. 19, okr. Pelhřimov – podle křestního listu vnuka (1924), citováno v dopise pravnuka.",
        "Podle rodinného rodokmenu měl nejméně dva další syny; syn jednoho z nich byl major armády USA, který v roce 1945 navštívil Václava Votavu (*1899) v Mostě."
      ],
      sources: [
        "Dopis Václava Votavy (*1933, Chomutov) Obecnímu úřadu Těchobuz, okr. Pelhřimov (nedatováno) – cituje křestní list Václava Votavy (*1899) z 9. 9. 1924 a výměr o domovském právu z 8. 9. 1940",
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)",
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)"
      ],
      scans: [
        {"f":"img/dopis_vaclav_votava_techobuz.jpg","t":"Dopis Václava Votavy (*1933) obecnímu úřadu v Těchobuzi"},
        {"f":"img/rodokmen_kresba_votava.jpg","t":"Ručně kreslený rodokmen Votavů"},
        {"f":"img/1899_krestni_list_vaclav_votava_sous.jpg","t":"Křest syna/vnuka Václava, Souš 1899"}
      ]
    },
    {
      id: "antonie_m",
      name: "Antonie Votavová",
      maiden: "Michalová",
      line: "michal",
      cert: "D",
      b: {"date":"neznámé (odhad ~1845)","year":1845,"approx":true},
      spouse: "stepan_v",
      notes: [
        "Matka Václava Votavy (*1868), z Těchobuze č. p. 19."
      ],
      sources: [
        "Dopis Václava Votavy (*1933, Chomutov) Obecnímu úřadu Těchobuz, okr. Pelhřimov (nedatováno) – cituje křestní list Václava Votavy (*1899) z 9. 9. 1924 a výměr o domovském právu z 8. 9. 1940"
      ]
    },
    {
      id: "josef_c",
      name: "Josef Čapek",
      line: "capek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1875)","year":1875,"approx":true},
      father: "karel_c",
      mother: "marie_o",
      spouse: "marie_f",
      notes: [
        "Otec Jany Votavové (*1903 Mladá Boleslav). Syn Karla Čapka, domkáře v Rabakově č. 19 (okr. Sobotka), a Marie Otové (?) z Kchleb č. 53 (okr. Nymburk).",
        "Později bydlel s manželkou v Komořanech u Mostu (dopis vnuka)."
      ],
      sources: [
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Úmrtní list Jany Votavové, MNV Most (vydán 15. 8. 1984)",
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134",
        "Dopis Václava Votavy (*1933) vnučce Aničce s tabulkou dat předků (po r. 2007) – rodinná paměť"
      ],
      scans: [
        {"f":"img/1903_krestni_list_jana_capkova_mlada_boleslav.jpg","t":"Křest dcery/vnučky Jany, Mladá Boleslav 1903"}
      ]
    },
    {
      id: "marie_f",
      name: "Marie Čapková",
      maiden: "Tůkalová",
      line: "fukal",
      cert: "D",
      b: {"date":"neznámé (odhad ~1878)","year":1878,"approx":true},
      father: "jan_t",
      mother: "frantiska_s",
      spouse: "josef_c",
      notes: [
        "Matka Jany Votavové (*1903). Dcera Jana Tůkala, baráčníka v Kosíčku (?) č. 52 (?), a Františky roz. Šnajdrové z Pojedic (?) č. 9, okr. Libáň (křestní list dcery 1924).",
        "Rodné příjmení: Tůkalová (křestní list 1924), Tukalová (úmrtní list dcery 1984); „Fukalová“ (rodný list vnuka 1956) je chyba opisu."
      ],
      sources: [
        "Rodný list Václava Votavy (*1933), MNV Most (vydán 17. 7. 1956)",
        "Úmrtní list Jany Votavové, MNV Most (vydán 15. 8. 1984)",
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134"
      ],
      scans: [
        {"f":"img/1903_krestni_list_jana_capkova_mlada_boleslav.jpg","t":"Křest dcery/vnučky Jany, Mladá Boleslav 1903"}
      ]
    },
    {
      id: "vaclav_c",
      name: "Václav Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"21. 7. 1868","year":1868,"place":"Hředle č. p. 37"},
      d: {"date":"22. 11. 1938","year":1938,"place":"Beroun-Lištice č. p. 229"},
      cause: "zápal plic a pohrudnice, srdeční vada",
      father: "matej_c",
      mother: "antonie_d",
      spouse: "anna_vl",
      occ: "rolník na Lištici č. p. 83, později č. p. 229 (Beroun III)",
      marriage: "19. 5. 1894, Beroun – s Annou Vlasákovou",
      notes: [
        "Otec Karla Červenky (*1906); rolník v Berouně III na Lištici (křestní a rodný list vnučky 1933).",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)",
        "Křestní a rodný list Anny Červenkové (*1933), fara Borek, kniha pokřtěných XIV, sv. 64, list 2 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "anna_vl",
      name: "Anna Červenková",
      maiden: "Vlasáková",
      line: "vlasak",
      cert: "D",
      b: {"date":"20. 11. 1871","year":1871,"place":"Zbečno"},
      d: {"date":"1946","year":1946,"place":"Beroun-Lištice č. p. 229"},
      father: "frantisek_vl",
      mother: "marie_se",
      spouse: "vaclav_c",
      marriage: "19. 5. 1894, Beroun – s Václavem Červenkou",
      notes: [
        "Dcera Františka Vlasáka ze mlýna v Račicích, rolníka na Lištici č. 83, a Marie Semencové z Dubiny u Zbečna č. 45 (rodopis).",
        "V rodném listu vnučky (1933) uvedena „ze Sýkořice č. p. 14“, v rodopisu „ze Zbečna-Račic (mlýn)“ – sousední obce na Křivoklátsku, upřesnit v matrice.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)",
        "Křestní a rodný list Anny Červenkové (*1933), fara Borek, kniha pokřtěných XIV, sv. 64, list 2 (vydán 15. 7. 1946)",
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "karel_k",
      name: "Karel Klika",
      line: "klika",
      cert: "D",
      b: {"date":"neznámé (odhad ~1885)","year":1885,"approx":true,"place":"Býkoš"},
      father: "josef_k",
      mother: "marie_s",
      spouse: "ruzena_v",
      occ: "dělník v Suchomastech č. p. 14",
      notes: [
        "Otec Anny Klikové (*1913); narozen v Býkoši. Svědek na sňatku dcery 1933 (Karel Klika, dělník v Suchomastech)."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)",
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2"
      ],
      scans: [
        {"f":"img/1913_krestni_list_anna_klikova_suchomasty.jpg","t":"Křest dcery Anny, Suchomasty 1913"}
      ]
    },
    {
      id: "ruzena_v",
      name: "Růžena Kliková",
      maiden: "Valentová",
      line: "valenta",
      cert: "D",
      b: {"date":"neznámé (odhad ~1890)","year":1890,"approx":true,"place":"Čepirohy (Tschöppern), okr. Most"},
      mother: "anna_va",
      spouse: "karel_k",
      notes: [
        "Matka Anny Klikové (*1913), z Tschöppern (Čepirohy) č. p. 20, okr. Most.",
        "V křestním listu dcery uvedena jen matka Anna, dcera Vitála Valenty – otec neuveden, patrně nemanželská (?)."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)",
        "Rodný list Anny Červenkové (*1933), MNV Suchomasty, z rodné matriky fary Borek u Suchomast, sv. XIV, roč. 1933, str. 64, č. 2",
        "Oddací list Karla Červenky a Anny Klikové, fara Borek (u Suchomast), kniha oddaných IX, sv. 412, list 7 (vydán 15. 7. 1946)"
      ],
      scans: [
        {"f":"img/1913_krestni_list_anna_klikova_suchomasty.jpg","t":"Křest dcery Anny, Suchomasty 1913"}
      ]
    },
    {
      id: "josef_k",
      name: "Josef Klika",
      line: "klika",
      cert: "D",
      b: {"date":"neznámé (odhad ~1855)","year":1855,"approx":true},
      spouse: "marie_s",
      occ: "dělník v Býkoši č. p. 38",
      notes: [
        "Otec Karla Kliky."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)"
      ]
    },
    {
      id: "marie_s",
      name: "Marie Kliková",
      maiden: "Svobodová",
      line: "svoboda",
      cert: "D",
      b: {"date":"neznámé (odhad ~1858)","year":1858,"approx":true},
      spouse: "josef_k",
      notes: [
        "Matka Karla Kliky."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)"
      ]
    },
    {
      id: "anna_va",
      name: "Anna Valentová",
      line: "valenta",
      cert: "D",
      b: {"date":"neznámé (odhad ~1868)","year":1868,"approx":true},
      father: "vital_v",
      notes: [
        "Matka Růženy Valentové; dcera Vitála Valenty z Tschöppern (Čepirohy) č. p. 20."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)"
      ]
    },
    {
      id: "vital_v",
      name: "Vitál Valenta",
      line: "valenta",
      cert: "D",
      b: {"date":"neznámé (odhad ~1840)","year":1840,"approx":true},
      occ: "dělník v Tschöppern (Čepirohy) č. p. 20, okr. Most",
      notes: [
        "Děd Růženy Valentové z matčiny strany."
      ],
      sources: [
        "Křestní a rodný list Anny Klikové (*1913), fara Borek, kniha pokřtěných XIII, sv. 154, list 9 (vydán 15. 7. 1946)"
      ]
    },
    {
      id: "eda_v",
      name: "Eda Votava",
      line: "votava",
      cert: "R",
      b: {"date":"neznámé (odhad ~1903)","year":1903,"approx":true},
      father: "vaclav1868",
      mother: "barbora_l",
      notes: [
        "Sourozenec Václava Votavy (*1899) podle rodinného rodokmenu; data a pořadí neznámé."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "josef_v",
      name: "Josef Votava",
      line: "votava",
      cert: "R",
      b: {"date":"neznámé (odhad ~1903)","year":1903,"approx":true},
      father: "vaclav1868",
      mother: "barbora_l",
      notes: [
        "Sourozenec Václava Votavy (*1899) podle rodinného rodokmenu; data a pořadí neznámé."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "zdenka_v",
      name: "Zdeňka Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"neznámé (odhad ~1903)","year":1903,"approx":true},
      father: "vaclav1868",
      mother: "barbora_l",
      notes: [
        "Sourozenec Václava Votavy (*1899) podle rodinného rodokmenu; data a pořadí neznámé."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "anna_v",
      name: "Anna Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"neznámé (odhad ~1903)","year":1903,"approx":true},
      father: "vaclav1868",
      mother: "barbora_l",
      notes: [
        "Sourozenec Václava Votavy (*1899) podle rodinného rodokmenu; data a pořadí neznámé."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "anicka1984",
      name: "Anna Hromasová",
      line: "hromas",
      cert: "R",
      b: {"date":"3. 1. 1984","year":1984},
      mother: "jana1958",
      alive: true,
      notes: [
        "Dcera Jany Hromasové, roz. Votavové (rodinný rodokmen); v kalendáři „Anička Hromasová“."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jan_jv",
      name: "Jan Votava",
      line: "votava",
      cert: "R",
      b: {"date":"neznámé (odhad ~1958)","year":1958,"approx":true},
      father: "jiri1926",
      notes: [
        "Syn Jiřího Votavy (*1926) podle rodinného rodokmenu; data neznámá."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "lenka_v",
      name: "Lenka (Votická?)",
      line: "voticky",
      cert: "R",
      b: {"date":"neznámé (odhad ~1980)","year":1980,"approx":true},
      father: "ivo1955",
      alive: true,
      notes: [
        "Dcera Iva Votického (*1955) podle rodinného rodokmenu; příjmení a data neznámá."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "jana_v",
      name: "Jana (Votická?)",
      line: "voticky",
      cert: "R",
      b: {"date":"neznámé (odhad ~1980)","year":1980,"approx":true},
      father: "ivo1955",
      alive: true,
      notes: [
        "Dcera Iva Votického (*1955) podle rodinného rodokmenu; příjmení a data neznámá."
      ],
      sources: [
        "Ručně kreslený rodokmen Votavů (rodina, nedatováno)"
      ]
    },
    {
      id: "karel_c",
      name: "Karel Čapek",
      line: "capek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1845)","year":1845,"approx":true},
      spouse: "marie_o",
      occ: "domkář v Rabakově č. 19, okr. Sobotka",
      notes: [
        "Otec Josefa Čapka, děd Jany Votavové (*1903)."
      ],
      sources: [
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134"
      ],
      scans: [
        {"f":"img/1903_krestni_list_jana_capkova_mlada_boleslav.jpg","t":"Křest dcery/vnučky Jany, Mladá Boleslav 1903"}
      ]
    },
    {
      id: "marie_o",
      name: "Marie Čapková",
      maiden: "Otová (?)",
      line: "ota",
      cert: "D",
      b: {"date":"neznámé (odhad ~1848)","year":1848,"approx":true,"place":"Kchleby č. p. 53, okr. Nymburk"},
      spouse: "karel_c",
      notes: [
        "Matka Josefa Čapka; čtení příjmení nejisté."
      ],
      sources: [
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134"
      ]
    },
    {
      id: "jan_t",
      name: "Jan Tůkal",
      line: "fukal",
      cert: "D",
      b: {"date":"neznámé (odhad ~1845)","year":1845,"approx":true},
      spouse: "frantiska_s",
      occ: "baráčník v Kosíčku (?) č. 52 (?)",
      notes: [
        "Otec Marie Čapkové, roz. Tůkalové."
      ],
      sources: [
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134"
      ],
      scans: [
        {"f":"img/1903_krestni_list_jana_capkova_mlada_boleslav.jpg","t":"Křest dcery/vnučky Jany, Mladá Boleslav 1903"}
      ]
    },
    {
      id: "frantiska_s",
      name: "Františka Tůkalová",
      maiden: "Šnajdrová",
      line: "snajdr",
      cert: "D",
      b: {"date":"neznámé (odhad ~1848)","year":1848,"approx":true,"place":"Pojedice (?) č. p. 9, okr. Libáň"},
      spouse: "jan_t",
      notes: [
        "Matka Marie Čapkové, roz. Tůkalové; čtení místa nejisté."
      ],
      sources: [
        "Křestní list Jany Čapkové, děkanský úřad Mladá Boleslav (9. 4. 1924) – dle křestní matriky Ml. Boleslav od r. 1903, fol. 134"
      ]
    },
    {
      id: "martin_l",
      name: "Martin Lodl",
      line: "lodl",
      cert: "D",
      b: {"date":"neznámé (odhad ~1840)","year":1840,"approx":true},
      spouse: "anna_f",
      occ: "horník v Souši č. 57 (?)",
      notes: [
        "Otec Barbory Votavové, roz. Lodlové."
      ],
      sources: [
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)"
      ],
      scans: [
        {"f":"img/1899_krestni_list_vaclav_votava_sous.jpg","t":"Křest syna/vnuka Václava, Souš 1899"}
      ]
    },
    {
      id: "anna_f",
      name: "Anna Lodlová",
      maiden: "Forejtová",
      line: "forejt",
      cert: "D",
      b: {"date":"neznámé (odhad ~1843)","year":1843,"approx":true},
      spouse: "martin_l",
      notes: [
        "Matka Barbory Votavové; původem „z ? (Věka?) č. 91“ – čtení místa nejisté."
      ],
      sources: [
        "Křestní list Václava Votavy (*1899), farní úřad Souš (Pfarrkirche zu Tschausch) č. 631, 9. 9. 1924 – dle matriky tom. 14, fol. 79 (?)"
      ]
    },
    {
      id: "vaclav1895",
      name: "Václav Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"17. 2. 1895","year":1895,"place":"Beroun-Lištice č. p. 83"},
      father: "vaclav_c",
      mother: "anna_vl",
      occ: "rolník na Lištici č. p. 229",
      marriage: "18. 11. 1923, Beroun – s Marií Petrákovou (*2. 3. 1897)",
      notes: [
        "Bratr Karla Červenky (*1906). Manželka Marie, dcera Václava Petráka, mistra tkalcovského ze Závodí, a Anny Mengerové z Hýskova č. 109.",
        "Rodopis, ze kterého pochází celá linie Červenků, byl sestaven pro něj a jeho manželku.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "jan1898",
      name: "Jan Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"17. 1. 1898","year":1898,"place":"Beroun-Lištice č. p. 83"},
      father: "vaclav_c",
      mother: "anna_vl",
      occ: "modelář, hajný v Horním Ostrovci u Písku",
      marriage: "10. 2. 1923 – s Marií Šlégrovou",
      notes: [
        "Bratr Karla Červenky. Manželka Marie, dcera Bohuslava Šlégra, obuvníka v Berouně na Lištici č. 292, a Julie Pechové ze Svaté č. 44.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "josef1899c",
      name: "Josef Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"11. 8. 1899","year":1899,"place":"Beroun-Lištice č. p. 83"},
      d: {"date":"13. 3. (rok v rodopisu chybí)","place":"Beroun č. p. 222"},
      cause: "srdeční vada",
      father: "vaclav_c",
      mother: "anna_vl",
      occ: "zámečník v Berouně č. p. 222",
      marriage: "7. 2. 1926 – s Marií Sládkovou",
      notes: [
        "Bratr Karla Červenky. Manželka Marie, dcera Antonína Sládka, dělníka v Berouně č. 222, a Anny Maštalířové z Berouna.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "frantisek1901c",
      name: "František Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"8. 7. 1901","year":1901,"place":"Beroun-Lištice č. p. 83"},
      d: {"date":"6. 11. 1921","year":1921,"place":"Beroun-Lištice č. p. 83"},
      cause: "tuberkulóza",
      father: "vaclav_c",
      mother: "anna_vl",
      occ: "malíř pokojů",
      notes: [
        "Bratr Karla Červenky.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "matej_c",
      name: "Matěj Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"3. 4. 1825","year":1825,"place":"Hředle č. p. 37"},
      d: {"date":"13. 2. 1905","year":1905,"place":"Hředle č. p. 37"},
      father: "jakub1789",
      mother: "veronika_s",
      occ: "rolník ve Hředlích č. p. 37",
      marriage: "25. 11. 1851, Zdice – s Antonií Divišovou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "antonie_d",
      name: "Antonie Červenková",
      maiden: "Divišová",
      line: "divis",
      cert: "D",
      b: {"date":"28. 7. 1822","year":1822,"place":"Černín č. p. 7"},
      father: "matej_d",
      mother: "josefa_m",
      marriage: "25. 11. 1851, Zdice – s Matějem Červenkou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "matej_d",
      name: "Matěj Diviš",
      line: "divis",
      cert: "D",
      b: {"date":"neznámé (odhad ~1790)","year":1790,"approx":true},
      spouse: "josefa_m",
      occ: "rolník v Černíně č. p. 7",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "josefa_m",
      name: "Josefa Divišová",
      maiden: "Merhautová",
      line: "merhaut",
      cert: "D",
      b: {"date":"neznámé (odhad ~1795)","year":1795,"approx":true,"place":"Zdice"},
      spouse: "matej_d",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "jakub1789",
      name: "Jakub Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"27. 5. 1789","year":1789,"place":"Hředle č. p. 37"},
      d: {"date":"13. 12. 1860","year":1860,"place":"Hředle č. p. 37"},
      father: "jakub1750",
      mother: "anna_h",
      occ: "rolník ve Hředlích č. p. 37",
      marriage: "24. 2. 1811, Všeradice – s Veronikou Skálovou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "veronika_s",
      name: "Veronika Červenková",
      maiden: "Skálová",
      line: "skala",
      cert: "D",
      b: {"date":"19. 8. 1791","year":1791,"place":"Vinařice č. p. 24"},
      d: {"date":"8. 4. 1851","year":1851,"place":"Hředle č. p. 37"},
      father: "jiri_s",
      mother: "eva_k",
      marriage: "24. 2. 1811, Všeradice – s Jakubem Červenkou",
      notes: [
        "Z Vinařic č. 28.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "jiri_s",
      name: "Jiří Skála",
      line: "skala",
      cert: "D",
      b: {"date":"neznámé (odhad ~1760)","year":1760,"approx":true},
      spouse: "eva_k",
      occ: "Vinařice č. p. 28",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "eva_k",
      name: "Eva Skálová",
      maiden: "Kalousová",
      line: "kalous",
      cert: "D",
      b: {"date":"neznámé (odhad ~1765)","year":1765,"approx":true,"place":"Býkoš"},
      spouse: "jiri_s",
      notes: [
        "Z Býkoše – odkud pocházel i Karel Klika (*~1885), děd Anny Červenkové (*1933) z matčiny strany.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "jakub1750",
      name: "Jakub Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"8. 7. 1750","year":1750,"place":"Hředle č. p. 37"},
      d: {"date":"2. 7. 1818","year":1818,"place":"Hředle č. p. 37"},
      father: "pavel1716",
      mother: "ludmila_d",
      occ: "rolník ve Hředlích č. p. 37",
      marriage: "17. 9. 1769, Žebrák – s Annou Holickou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "anna_h",
      name: "Anna Červenková",
      maiden: "Holická",
      line: "holicky",
      cert: "D",
      b: {"date":"neznámé (odhad ~1750)","year":1750,"approx":true,"place":"Hředle"},
      father: "daniel_h",
      mother: "katerina_z",
      marriage: "17. 9. 1769, Žebrák – s Jakubem Červenkou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "daniel_h",
      name: "Daniel Holický",
      line: "holicky",
      cert: "D",
      b: {"date":"neznámé (odhad ~1720)","year":1720,"approx":true},
      spouse: "katerina_z",
      occ: "rolník ve Hředlích",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "katerina_z",
      name: "Kateřina Holická",
      maiden: "Zymová",
      line: "zyma",
      cert: "D",
      b: {"date":"neznámé (odhad ~1725)","year":1725,"approx":true},
      spouse: "daniel_h",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "pavel1716",
      name: "Pavel Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"26. 1. 1716","year":1716,"place":"Hředle"},
      d: {"date":"6. 8. 1761","year":1761,"place":"Hředle"},
      father: "vaclav1674",
      mother: "dorota_n",
      occ: "rolník ve Hředlích",
      marriage: "asi 1739 – s Ludmilou Drapalovou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "ludmila_d",
      name: "Ludmila Červenková",
      maiden: "Drapalová",
      line: "drapal",
      cert: "D",
      b: {"date":"neznámé (odhad ~1718)","year":1718,"approx":true},
      spouse: "pavel1716",
      marriage: "asi 1739 – s Pavlem Červenkou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "vaclav1674",
      name: "Václav Červenka",
      line: "cervenka",
      cert: "D",
      b: {"date":"asi 1674","year":1674,"approx":true},
      d: {"date":"1. 3. 1730","year":1730,"place":"Hředle"},
      spouse: "dorota_n",
      occ: "rolník ve Hředlích",
      marriage: "30. 11. 1696, Žebrák – s Dorotou Novou",
      notes: [
        "Nejstarší známý Červenka. V rodopisu na 1. stránce chybně „oddán 30. 11. 1896“, na 2. stránce správně 1696.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ],
      scans: [
        {"f":"img/rodopis_cervenka_1.jpg","t":"Rodopis Červenků, s. 1"},
        {"f":"img/rodopis_cervenka_2.jpg","t":"Rodopis Červenků, s. 2"},
        {"f":"img/rodopis_cervenka_listice.jpg","t":"Rodopis Červenků – rodina na Lištici"}
      ]
    },
    {
      id: "dorota_n",
      name: "Dorota Červenková",
      maiden: "Nová",
      line: "novy",
      cert: "D",
      b: {"date":"15. 1. 1679","year":1679,"place":"Chlustina"},
      d: {"date":"2. 11. 1752","year":1752,"place":"Hředle"},
      father: "jan_n",
      mother: "ludmila_n",
      marriage: "30. 11. 1696, Žebrák – s Václavem Červenkou",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "jan_n",
      name: "Jan Nový",
      line: "novy",
      cert: "D",
      b: {"date":"neznámé (odhad ~1650)","year":1650,"approx":true},
      spouse: "ludmila_n",
      occ: "soused (usedlík) v Chlustině",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "ludmila_n",
      name: "Ludmila Nová",
      line: "nezname",
      cert: "D",
      b: {"date":"neznámé (odhad ~1652)","year":1652,"approx":true},
      spouse: "jan_n",
      notes: [
        "Rodné příjmení neuvedeno.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "frantisek_vl",
      name: "František Vlasák",
      line: "vlasak",
      cert: "D",
      b: {"date":"neznámé (odhad ~1840)","year":1840,"approx":true},
      spouse: "marie_se",
      occ: "mlynář v Račicích, rolník na Lištici č. 83",
      notes: [
        "Otec Anny Červenkové, roz. Vlasákové.",
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    },
    {
      id: "marie_se",
      name: "Marie Vlasáková",
      maiden: "Semencová",
      line: "semenec",
      cert: "D",
      b: {"date":"neznámé (odhad ~1845)","year":1845,"approx":true,"place":"Dubina u Zbečna č. p. 45"},
      spouse: "frantisek_vl",
      notes: [
        "Údaje podle strojopisného rodopisu Červenků – ověřit v matrikách."
      ],
      sources: [
        "Strojopisný rodopis „Rodokmen Václava Červenky a Marie roz. Petrákové, Lištice č. 229“ (rodinný, autor a citované prameny neuvedeny)"
      ]
    }
  ]
};

// ── Origin map and historical context ─────────────────────────────
window.RODOKMEN.places = [
  {"name":"Suchomasty","lat":49.896,"lon":14.058,"line":"cervenka","note":"Karel a Anna Červenkovi („děda a babička ze Suchomast“)","anchor":"start"},
  {"name":"Karviná","lat":49.856,"lon":18.55,"line":"zettelmann","note":"Zettelmannovi (bydliště 1963)"},
  {"name":"Těchobuz","lat":49.495,"lon":14.975,"line":"votava","note":"domovská obec Votavů (Štěpán Votava, č. p. 19)","anchor":"start"}
];
window.RODOKMEN.story = [
  {"line":"votava","title":"Votavovi","text":["Votavové pocházejí z Českomoravské vrchoviny. Štěpán Votava a Antonie, roz. Michalová, žili v Těchobuzi č. p. 19 na Pelhřimovsku a jejich syn Václav se narodil roku 1868 v Pravoníně.","Podle rodinné tradice přišel Václav (*1868) jako malý chlapec na Mostecko, kde se otvíraly uhelné šachty; horníkem v Souši byl i jeho otec Štěpán. Václav se oženil s Barborou Lodlovou, dcerou souškého horníka, a dožil se 95 let. Jeho syn Václav (*1899) se narodil v Souši a byl také horníkem. Domovské právo v Těchobuzi mu v roce 1940 pomohlo, aby ho úřady v zabraném pohraničí považovaly za Čecha.","Roku 1924 se Václav (*1899) oženil v Mostě s Janou Čapkovou z Mladé Boleslavi, jejíž rodiče pak žili v Komořanech u Mostu. Měli čtyři děti: Jiřího (*1926), Vlastu (*1927), Václava (*1933) a Vladimíra (*1942). Václav (*1933), chemik, se roku 1956 oženil v Kolíně s Annou Červenkovou ze Suchomast a jejich syn Jan se narodil roku 1957 v Berouně.","Po válce, roku 1945, navštívil rodinu v Mostě bratranec – major armády USA, vnuk Štěpána Votavy z větve, která se vystěhovala do Ameriky."],"lines":["votava","lodl","forejt","capek","fukal","ota","snajdr","michal"]},
  {"line":"zettelmann","lines":["zettelmann","hrazdilek","blazek","jerabek"],"title":"Zettelmannovi a Hrazdílkovi","text":["František Zettelmann se narodil roku 1940 v Polouvsí na Novojičínsku, Helena Hrazdílková téhož roku v Heršpicích u Vyškova. V roce 1963 žili v Karviné, kde se jim narodila dcera Šárka."]},
  {"line":"cervenka","lines":["cervenka","klika","valenta","vlasak","svoboda","divis","merhaut","skala","kalous","holicky","zyma","drapal","novy","semenec"],"title":"Červenkovi a Klikovi","text":["Červenkové byli po pět generací rolníky ve Hředlích č. p. 37 u Žebráka. Nejstarší známý předek Václav Červenka (asi 1674–1730) se roku 1696 oženil v Žebráku s Dorotou Novou z Chlustiny. Linie pokračuje přes Pavla (1716), dva Jakuby (1750, 1789) a Matěje (1825).","Matějův syn Václav (1868–1938) se usadil jako rolník v Berouně na Lištici a oženil se s Annou Vlasákovou z mlynářské rodiny z Račic u Zbečna. Z jejich pěti synů je nejmladší Karel (*1906) děd Jana Votavy.","Karel Červenka se v lednu 1933 oženil v kostele sv. Mikuláše v Borku u Suchomast s Annou Klikovou, dcerou dělníka Karla Kliky z Býkoše a Růženy Valentové z Čepiroh (Tschöppern) u Mostu.","Linie do 17. století pochází z rodinného strojopisného rodopisu; jednotlivé údaje se ještě ověřují v matrikách."]}
];
window.RODOKMEN.timeline = [
  {"y":1940,"t":"František Zettelmann se rodí v Polouvsí, Helena Hrazdílková v Heršpicích"},
  {"y":1963,"t":"Zettelmannovi žijí v Karviné-Ráji, narodila se dcera Šárka"},
  {"y":1868,"t":"Václav Votava se rodí v Pravoníně"},
  {"y":1899,"t":"Václav Votava se rodí v Souši u Mostu"},
  {"y":1933,"t":"Sňatek Karla Červenky a Anny Klikové v Borku u Suchomast (7. 1.)"},
  {"y":1956,"t":"Sňatek Václava Votavy a Anny Červenkové v Kolíně (11. 8.)"},
  {"y":1696,"t":"Sňatek Václava Červenky a Doroty Nové v Žebráku – nejstarší známé datum rodu"},
  {"y":1894,"t":"Sňatek Václava Červenky a Anny Vlasákové v Berouně"},
  {"y":1924,"t":"Sňatek Václava Votavy a Jany Čapkové v Mostě (18. 10.)"},
  {"y":1940,"t":"Výměr o domovském právu v Těchobuzi pro Václava Votavu (*1899) a jeho rodinu"}
];

// Documented migrations; kind: "doc" = documented, "rail" = probable route by train, "hyp" = hypothesis
window.RODOKMEN.moves = [
  {"who":"František Zettelmann","when":"do 1963","line":"zettelmann","kind":"doc","path":[[49.6,17.96],[49.856,18.55]],"note":"z Polouvsí do Karviné (bydliště podle rodného listu dcery)"},
  {"who":"Václav Votava (*1868)","when":"kolem 1872","line":"votava","kind":"hyp","path":[[49.635,14.945],[50.087,14.421],[50.503,13.636]],"note":"z Pravonína na Mostecko, kde se otvíraly šachty (rodinná tradice)"},
  {"who":"Jana Čapková","when":"do 1926","line":"capek","kind":"doc","path":[[50.411,14.906],[50.52,13.68]],"note":"z Mladé Boleslavi do Souše u Mostu (sňatek s Václavem Votavou)"}
];

// Historical events for the context column right of the year ruler; y2 = end year of a period (drawn as a band), major = shown even when zoomed out
window.RODOKMEN.events = [
  {"y":1867,"t":"Rakousko-uherské vyrovnání","s":"Rakousko-Uhersko"},
  {"y":1914,"y2":1918,"t":"První světová válka","s":"1. sv. válka","major":true},
  {"y":1918,"t":"Vznik Československa","s":"ČSR","major":true},
  {"y":1938,"t":"Mnichovská dohoda – Most a Chomutov připadly Německu","s":"Mnichov"},
  {"y":1939,"y2":1945,"t":"Druhá světová válka","s":"2. sv. válka","major":true},
  {"y":1945,"t":"Odsun Němců, dosídlování pohraničí (Most, Chomutov)","s":"odsun Němců"},
  {"y":1948,"t":"Únorový převrat","s":"Únor 1948"},
  {"y":1968,"t":"Pražské jaro a okupace","s":"srpen 1968"},
  {"y":1989,"t":"Sametová revoluce","s":"listopad 1989","major":true},
  {"y":1993,"t":"Vznik České republiky","s":"vznik ČR"},
  {"y":2004,"t":"Vstup do Evropské unie","s":"vstup do EU"},
  {"y":1848,"t":"Zrušení roboty","s":"konec roboty"},
  {"y":1872,"t":"Rozmach těžby hnědého uhlí na Mostecku","s":"uhlí na Mostecku"},
  {"y":1680,"t":"Selské povstání a první robotní patent","s":"robotní patent"},
  {"y":1748,"t":"Tereziánský katastr","s":"tereziánský katastr"},
  {"y":1781,"t":"Zrušení nevolnictví","s":"konec nevolnictví"}
];
