// datatool.js – load data.js as an object, apply edits in code, write it back in one canonical format.
// Use this instead of text/regex edits of data.js (regex edits caused misplaced fields and stale cards).
//
//   const T = require('./datatool');
//   const d = T.load();               // window.RODOKMEN object
//   const p = T.person(d, 'jan1957');   // throws if the id does not exist
//   p.d = { date: '…', year: 1915 };  // edit fields directly
//   T.save(d);                        // rewrites data.js (validate.js runs in build.sh)
'use strict';
const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, 'data.js');

// Field order inside a person record – keeps diffs readable.
const ORDER = ['id', 'name', 'maiden', 'line', 'cert', 'b', 'd', 'cause', 'father', 'mother', 'spouse', 'siblings', 'alive', 'occ', 'marriage', 'notes', 'sources', 'scans'];

function load() {
  const sandbox = {};
  new Function('window', fs.readFileSync(FILE, 'utf8'))(sandbox);
  return sandbox.RODOKMEN;
}

function person(d, id) {
  const p = d.people.find(x => x.id === id);
  if (!p) throw new Error(`no person with id "${id}"`);
  return p;
}

const j = v => JSON.stringify(v);
// key-order-independent serialization for the round-trip check
const canon = v => Array.isArray(v) ? '[' + v.map(canon).join(',') + ']'
  : v && typeof v === 'object' ? '{' + Object.keys(v).sort().map(k => j(k) + ':' + canon(v[k])).join(',') + '}' : j(v);

function fmtPerson(p) {
  const keys = [...ORDER.filter(k => k in p), ...Object.keys(p).filter(k => !ORDER.includes(k))];
  const lines = keys.map(k => {
    const v = p[k];
    if (Array.isArray(v) && v.length && (k === 'notes' || k === 'sources' || k === 'scans'))
      return `      ${k}: [\n${v.map(x => '        ' + j(x)).join(',\n')}\n      ]`;
    return `      ${k}: ${j(v)}`;
  });
  return `    {\n${lines.join(',\n')}\n    }`;
}

function fmtList(name, arr) {
  return `window.RODOKMEN.${name} = [\n${arr.map(x => '  ' + j(x)).join(',\n')}\n];\n`;
}

function save(d) {
  const { people, places, story, timeline, moves, events, ...head } = d;
  let s = '// Family tree of Jiří Votava – data. GENERATED by datatool.js – edit via datatool, not by hand/regex.\n';
  s += '// cert: M = read in a parish/civil register, D = other document, R = family tradition, K = candidate / unverified\n';
  s += 'window.RODOKMEN = {\n';
  for (const [k, v] of Object.entries(head)) s += `  ${k}: ${JSON.stringify(v, null, 2).replace(/\n/g, '\n  ')},\n`;
  s += `  people: [\n${people.map(fmtPerson).join(',\n')}\n  ]\n};\n\n`;
  s += '// ── Origin map and historical context ─────────────────────────────\n';
  if (places) s += fmtList('places', places);
  if (story) s += fmtList('story', story);
  if (timeline) s += fmtList('timeline', timeline);
  s += '\n// Documented migrations; kind: "doc" = documented, "rail" = probable route by train, "hyp" = hypothesis\n';
  if (moves) s += fmtList('moves', moves);
  s += '\n// Historical events for the context column right of the year ruler; y2 = end year of a period (drawn as a band), major = shown even when zoomed out\n';
  if (events) s += fmtList('events', events);
  fs.writeFileSync(FILE, s);
  // round-trip check: the written file must load to the identical object
  if (canon(load()) !== canon(d)) throw new Error('round-trip mismatch after save');
}

module.exports = { load, save, person, canon };
