// Family tree of Jiří Votava – data. GENERATED by datatool.js – edit via datatool, not by hand/regex.
// cert: M = read in a parish/civil register, D = other document, R = family tradition, K = candidate / unverified
window.RODOKMEN = {
  updated: "8. 10. 2026",
  root: "jiri1987",
  publicLiving: "names",
  lines: {
    "votava": "Votava",
    "cervenka": "Červenka",
    "zettelmann": "Zettelmann",
    "hrazdilek": "Hrazdílek",
    "blazek": "Blažek",
    "jerabek": "Jeřábek",
    "hromas": "Hromas",
    "voticky": "Votický",
    "nezname": "zatím neznámý"
  },
  people: [
    {
      id: "jiri1987",
      name: "Jiří Votava",
      line: "votava",
      cert: "D",
      b: {"date":"2. 2. 1987","year":1987,"place":"Vítkov č. p. 89, okr. Opava"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Výchozí osoba rodokmenu. Druhý syn Jana a Šárky Votavových."
      ],
      sources: [
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "martin1984",
      name: "Martin Votava",
      line: "votava",
      cert: "D",
      b: {"date":"14. 8. 1984","year":1984,"place":"Vítkov, Opavská č. p. 89, okr. Opava"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "První syn Jana a Šárky."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jan1993",
      name: "Jan Votava",
      line: "votava",
      cert: "D",
      b: {"date":"13. 3. 1993","year":1993,"place":"Chomutov (nemocnice)"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Třetí syn Jana a Šárky, v rodině „Jenda“."
      ],
      sources: [
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "frantisek2000",
      name: "František Votava",
      line: "votava",
      cert: "D",
      b: {"date":"16. 6. 2000","year":2000,"place":"Chomutov (nemocnice)"},
      father: "jan1957",
      mother: "sarka1963",
      alive: true,
      notes: [
        "Čtvrtý syn Jana a Šárky."
      ],
      sources: [
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jan1957",
      name: "Jan Votava",
      line: "votava",
      cert: "D",
      b: {"date":"5. 3. 1957","year":1957,"place":"Beroun"},
      father: "vaclav1933",
      mother: "anna1933",
      spouse: "sarka1963",
      alive: true,
      occ: "student (1984); soukromý podnikatel (1993); Ing., podnikatel (2000)",
      notes: [
        "Rodiče Václav Votava a Anna, roz. Červenková – podle rodných listů synů.",
        "Bydliště podle rodných listů synů: Vítkov, okr. Opava (1984, 1987), Jirkov, okr. Chomutov (1993, 2000).",
        "Datum a místo sňatku se Šárkou Zettelmannovou zatím nezjištěno."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "sarka1963",
      name: "Šárka Votavová",
      maiden: "Zettelmannová",
      line: "zettelmann",
      cert: "D",
      b: {"date":"14. 4. 1963","year":1963,"place":"Karviná 4 – Ráj (nemocnice), okr. Karviná"},
      father: "frantisek1940",
      mother: "helena1940",
      spouse: "jan1957",
      alive: true,
      occ: "cenzurantka (1984); účetní (1993); referentka (2000)",
      notes: [
        "V roce 1963 bydleli rodiče v Karviné 4 – Ráj."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)"
      ]
    },
    {
      id: "jana1958",
      name: "Jana Hromasová",
      maiden: "Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"17. 5. 1958","year":1958},
      father: "vaclav1933",
      mother: "anna1933",
      spouse: "karel1964",
      alive: true,
      notes: [
        "Sestra Jana Votavy (*1957)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1964",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"9. 9. 1964","year":1964},
      father: "karel1937",
      mother: "vlasta1935",
      spouse: "jana1958",
      alive: true,
      notes: [
        "Manžel Jany Hromasové, roz. Votavové; v kalendáři „Karel Hromas (Beroun)“."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1986",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"27. 1. 1986","year":1986},
      mother: "jana1958",
      alive: true,
      notes: [
        "Syn Jany Hromasové, roz. Votavové; v kalendáři „Karel Hromas (Hokej)“.",
        "Otec v kalendáři výslovně neuveden – nejspíš Karel Hromas (*1964), manžel Jany (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1937",
      name: "Karel Hromas",
      line: "hromas",
      cert: "R",
      b: {"date":"2. 12. 1937","year":1937},
      notes: [
        "Otec Karla Hromase (*1964); v kalendáři „Karel Hromas (Rajč.)“."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vlasta1935",
      name: "Vlasta Hromasová",
      line: "nezname",
      cert: "R",
      b: {"date":"3. 3. 1935","year":1935},
      notes: [
        "Matka Karla Hromase (*1964) – v kalendáři „tchyně sestry Jany Votavové“.",
        "Rodné příjmení neznámé."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vaclav1933",
      name: "Václav Votava",
      line: "votava",
      cert: "D",
      b: {"date":"4. 9. 1933","year":1933},
      d: {"date":"4. 9. 2017","year":2017},
      father: "vaclav1899",
      mother: "jana1903",
      notes: [
        "Jako otec Jana Votavy (*1957) uveden na rodných listech jeho synů.",
        "Data narození a úmrtí podle rodinného kalendáře. Rok úmrtí je v kalendáři ručně opraven z 1947 na 2017 a úmrtí připadá na den 84. narozenin – ověřit (?)."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "anna1933",
      name: "Anna Votavová",
      maiden: "Červenková",
      line: "cervenka",
      cert: "D",
      b: {"date":"27. 2. 1933","year":1933},
      d: {"date":"2. 11. 2016","year":2016},
      father: "karel1906",
      mother: "anna1913",
      notes: [
        "V rodině „Hanka“. Rodné příjmení Červenková podle rodných listů vnuků.",
        "Data narození a úmrtí podle rodinného kalendáře."
      ],
      sources: [
        "Rodný list Martina Votavy, MěNV Vítkov, okr. Opava (vydán 23. 8. 1984)",
        "Rodný list Jiřího Votavy, MÚ Vítkov, kniha narození sv. 33/1, rok 1987, str. 144, poř. č. 46 (vydán 12. 4. 2018)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodný list Františka Votavy (*2000), MÚ Chomutov (vydán 20. 6. 2000)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jiri1926",
      name: "Jiří Votava",
      line: "votava",
      cert: "R",
      b: {"date":"3. 4. 1926","year":1926},
      d: {"date":"24. 4. 1980","year":1980},
      father: "vaclav1899",
      mother: "jana1903",
      spouse: "lidus1934",
      notes: [
        "Bratr Václava Votavy (*1933)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "lidus1934",
      name: "Liduš Votavová",
      line: "nezname",
      cert: "R",
      b: {"date":"23. 8. 1934","year":1934},
      d: {"date":"22. 8. 2004","year":2004},
      spouse: "jiri1926",
      notes: [
        "Manželka Jiřího Votavy (*1926).",
        "Rodné příjmení neznámé; „Liduš“ je nejspíš domácká podoba jména Ludmila (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jiri1954",
      name: "Jiří Votava",
      line: "votava",
      cert: "R",
      b: {"date":"4. 8. 1954","year":1954},
      d: {"date":"4. 3. 2008","year":2008},
      father: "jiri1926",
      notes: [
        "Syn Jiřího Votavy (*1926), bratranec Jana Votavy (*1957).",
        "Matka v kalendáři neuvedena."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vlasta1927",
      name: "Vlasta Votická",
      maiden: "Votavová",
      line: "votava",
      cert: "R",
      b: {"date":"2. 6. 1927","year":1927},
      d: {"date":"19. 4. 2008","year":2008},
      father: "vaclav1899",
      mother: "jana1903",
      spouse: "frantisek1919",
      notes: [
        "Sestra Václava Votavy (*1933)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "frantisek1919",
      name: "František Votický",
      line: "voticky",
      cert: "R",
      b: {"date":"9. 1. 1919","year":1919},
      d: {"date":"19. 6. 1982","year":1982},
      spouse: "vlasta1927",
      notes: [
        "Manžel Vlasty Votické, roz. Votavové."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "ivo1955",
      name: "Ivo Votický",
      line: "voticky",
      cert: "R",
      b: {"date":"16. 3. 1955","year":1955},
      mother: "vlasta1927",
      notes: [
        "Syn Vlasty Votické (*1927), bratranec Jana Votavy (*1957).",
        "Otec v kalendáři výslovně neuveden – nejspíš František Votický (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vladik1942",
      name: "Vladík Votava",
      line: "votava",
      cert: "R",
      b: {"date":"4. 1. 1942","year":1942},
      d: {"date":"7. 10. 1995","year":1995},
      father: "vaclav1899",
      mother: "jana1903",
      notes: [
        "Bratr Václava Votavy (*1933). „Vladík“ je nejspíš domácká podoba jména Vladimír (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "frantisek1940",
      name: "František Zettelmann",
      line: "zettelmann",
      cert: "D",
      b: {"date":"26. 11. 1940","year":1940,"place":"Polouvsí, okr. Nový Jičín"},
      d: {"date":"8. 4. 1999","year":1999},
      father: "frantisek_z",
      mother: "ludmila_b",
      occ: "řidič (1963)",
      notes: [
        "Datum úmrtí podle rodinného kalendáře.",
        "Na rodném listu vnuka Jana (1993) zapsán jako „František Zettelmann roz. Zetelmann“ – příjmení se mohlo psát i s jedním t."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodný list Jana Votavy (*1993), MÚ Chomutov (vydán 16. 3. 1993)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "helena1940",
      name: "Helena Zettelmannová",
      maiden: "Hrazdílková",
      line: "hrazdilek",
      cert: "D",
      b: {"date":"21. 10. 1940","year":1940,"place":"Heršpice, okr. Vyškov"},
      father: "vladimir_h",
      mother: "marie_j",
      occ: "zdravotní sestra (1963)",
      notes: [
        "Matka Šárky Votavové."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)",
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "vaclav1899",
      name: "Václav Votava",
      line: "votava",
      cert: "R",
      b: {"date":"25. 10. 1899","year":1899},
      d: {"date":"11. 12. 1968","year":1968},
      notes: [
        "V kalendáři „Děda (Most)“ – děda Jana Votavy (*1957) z otcovy strany. Most je nejspíš místo, kde žil (?)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "jana1903",
      name: "Jana Votavová",
      line: "nezname",
      cert: "R",
      b: {"date":"16. 5. 1903","year":1903},
      d: {"date":"29. 7. 1984","year":1984},
      notes: [
        "V kalendáři „Babička (Most)“ – matka Václava Votavy (*1933).",
        "Rodné příjmení zatím neznámé.",
        "V kalendáři je tištěné datum narození 19. 5. 1903 ručně opraveno na 16. 5. 1903."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "karel1906",
      name: "Karel Červenka",
      line: "cervenka",
      cert: "R",
      b: {"date":"29. 4. 1906","year":1906},
      d: {"date":"8. 9. 1984","year":1984},
      notes: [
        "V kalendáři „Děda (Suchomasty)“ – otec Anny Votavové (*1933)."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "anna1913",
      name: "Anna Červenková",
      line: "nezname",
      cert: "R",
      b: {"date":"3. 4. 1913","year":1913},
      d: {"date":"25. 5. 1983","year":1983},
      notes: [
        "V kalendáři „Babička (Suchomasty)“ – matka Anny Votavové (*1933).",
        "Rodné příjmení zatím neznámé."
      ],
      sources: [
        "Rodinný kalendář narozenin a úmrtí s ručními poznámkami Jana Votavy (*1957), doplněno 8. 10. 2026 – fotografie u rodiny"
      ]
    },
    {
      id: "frantisek_z",
      name: "František Zettelmann",
      line: "zettelmann",
      cert: "D",
      b: {"date":"neznámé (odhad ~1912)","year":1912,"approx":true},
      notes: [
        "Otec Františka Zettelmanna (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "ludmila_b",
      name: "Ludmila Zettelmannová",
      maiden: "Blažková",
      line: "blazek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1915)","year":1915,"approx":true},
      notes: [
        "Matka Františka Zettelmanna (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "vladimir_h",
      name: "Vladimír Hrazdílek",
      line: "hrazdilek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1912)","year":1912,"approx":true},
      notes: [
        "Otec Heleny Zettelmannové (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    },
    {
      id: "marie_j",
      name: "Marie Hrazdílková",
      maiden: "Jeřábková",
      line: "jerabek",
      cert: "D",
      b: {"date":"neznámé (odhad ~1915)","year":1915,"approx":true},
      notes: [
        "Matka Heleny Zettelmannové (*1940) podle rodného listu Šárky Zettelmannové (1963).",
        "Data narození a úmrtí zatím neznámá."
      ],
      sources: [
        "Rodný list Šárky Zettelmannové, MěNV Karviná (vydán 9. 6. 1963)"
      ]
    }
  ]
};

// ── Origin map and historical context ─────────────────────────────
window.RODOKMEN.places = [
  {"name":"Most","lat":50.503,"lon":13.636,"line":"votava","note":"Václav a Jana Votavovi („děda a babička z Mostu“)"},
  {"name":"Suchomasty","lat":49.896,"lon":14.058,"line":"cervenka","note":"Karel a Anna Červenkovi („děda a babička ze Suchomast“)","anchor":"start"},
  {"name":"Karviná","lat":49.856,"lon":18.55,"line":"zettelmann","note":"Zettelmannovi (bydliště 1963)"}
];
window.RODOKMEN.story = [
  {"line":"votava","title":"Votavovi","text":["Nejstarší známý Votava je Václav (*1899), kterému rodina říkala „děda z Mostu“. S Janou měl nejméně čtyři děti: Jiřího (*1926), Vlastu (*1927), Václava (*1933) a Vladíka (*1942).","Václav (*1933) si vzal Annu Červenkovou ze Suchomast. Jejich syn Jan se narodil roku 1957 v Berouně."]},
  {"line":"zettelmann","lines":["zettelmann","hrazdilek","blazek","jerabek"],"title":"Zettelmannovi a Hrazdílkovi","text":["František Zettelmann se narodil roku 1940 v Polouvsí na Novojičínsku, Helena Hrazdílková téhož roku v Heršpicích u Vyškova. V roce 1963 žili v Karviné, kde se jim narodila dcera Šárka."]}
];
window.RODOKMEN.timeline = [
  {"y":1940,"t":"František Zettelmann se rodí v Polouvsí, Helena Hrazdílková v Heršpicích"},
  {"y":1963,"t":"Zettelmannovi žijí v Karviné-Ráji, narodila se dcera Šárka"}
];

// Documented migrations; kind: "doc" = documented, "rail" = probable route by train, "hyp" = hypothesis
window.RODOKMEN.moves = [
  {"who":"František Zettelmann","when":"do 1963","line":"zettelmann","kind":"doc","path":[[49.6,17.96],[49.856,18.55]],"note":"z Polouvsí do Karviné (bydliště podle rodného listu dcery)"}
];

// Historical events for the context column right of the year ruler; y2 = end year of a period (drawn as a band), major = shown even when zoomed out
window.RODOKMEN.events = [
  {"y":1867,"t":"Rakousko-uherské vyrovnání","s":"Rakousko-Uhersko"},
  {"y":1914,"y2":1918,"t":"První světová válka","s":"1. sv. válka","major":true},
  {"y":1918,"t":"Vznik Československa","s":"ČSR","major":true},
  {"y":1938,"t":"Mnichovská dohoda – Most a Chomutov připadly Německu","s":"Mnichov"},
  {"y":1939,"y2":1945,"t":"Druhá světová válka","s":"2. sv. válka","major":true},
  {"y":1945,"t":"Odsun Němců, dosídlování pohraničí (Most, Chomutov)","s":"odsun Němců"},
  {"y":1948,"t":"Únorový převrat","s":"Únor 1948"},
  {"y":1968,"t":"Pražské jaro a okupace","s":"srpen 1968"},
  {"y":1989,"t":"Sametová revoluce","s":"listopad 1989","major":true},
  {"y":1993,"t":"Vznik České republiky","s":"vznik ČR"},
  {"y":2004,"t":"Vstup do Evropské unie","s":"vstup do EU"}
];
