#!/usr/bin/env node
// Prints the public version of data.js (used by build.sh instead of data.js).
// Living persons are reduced according to D.publicLiving, which only the family decides:
//   'names' (default) – name, line and links only; birth year rounded to 5 years (needed for the layout)
//   'full'            – everything as in data.js
// A person counts as living when alive === true, or when no death is known and they were born
// less than 100 years ago (unknown = treat as living).
'use strict';
const T = require('./datatool');
const D = T.load();
const mode = D.publicLiving || 'names';
if (!['names', 'full'].includes(mode)) { console.error(`public_data.js: unknown publicLiving "${mode}"`); process.exit(1); }

const now = new Date().getFullYear();
const living = p => p.alive === true || (!p.d && p.b && p.b.year >= now - 100);
const KEEP = ['id', 'name', 'maiden', 'line', 'cert', 'father', 'mother', 'spouse', 'siblings'];

let hidden = 0;
if (mode === 'names') {
  D.people = D.people.map(p => {
    if (!living(p)) return p;
    hidden++;
    const q = Object.fromEntries(KEEP.filter(k => k in p).map(k => [k, p[k]]));
    q.b = { year: Math.round(p.b.year / 5) * 5, approx: true };
    q.alive = true;
    q.priv = true;
    return q;
  });
}
process.stdout.write(`// PUBLIC data (living persons: ${mode}, ${hidden} reduced). GENERATED by public_data.js from data.js – do not edit.\n`);
process.stdout.write(`window.RODOKMEN=${JSON.stringify(D)};\n`);
